MATERIALS_ALPINE = [
    ( "AlpineSnow.Material.Gbx", [] ),
    ( "AlpineMountainWarp2.Material.Gbx", [ [ [ "Blend3", [ "AlpineMountainWarp2.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineMountainWarp.Material.Gbx", [ [ [ "Blend3", [ "AlpineMountainWarp.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineWarpShadowCaster.Material.Gbx", [] ),
    ( "AlpinePylonsWood.Material.Gbx", [ [ [ "Diffuse", [ "AlpinePylonsWood.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineSnowBorders.Material.Gbx", [ [ [ "Blend3", [ "AlpineSnowBorders.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineAsphalt.Material.Gbx", [ [ [ "Diffuse", [ "AlpineAsphaltDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineRoadWood.Material.Gbx", [ [ [ "Diffuse", [ "AlpineRoadWoodDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineTunnelOutside.Material.Gbx", [ [ [ "Diffuse", [ "AlpineTunnelDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineIce.Material.Gbx", [] ),
    ( "AlpineIceBorders.Material.Gbx", [ [ [ "Borders", [ "AlpineSnowBorders.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineIceCanyon.Material.Gbx", [ [ [ "Borders", [ "AlpineIceCanyonDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineRocks.Material.Gbx", [ [ [ "Blend3", [ "AlpineRocksDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineToundra.Material.Gbx", [] ),
    ( "AlpineHillToundra.Material.Gbx", [ [ [ "Blend3", [ "AlpineHill.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineHill.Material.Gbx", [ [ [ "Blend3", [ "AlpineHill.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineHillTree.Material.Gbx", [ [ [ "Diffuse", [ "AlpineHillTree.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineSnowTreesShadows.Material.Gbx", [] ),
    ( "AlpineTempleRocks.Material.Gbx", [ [ [ "Blend3", [ "AlpineTempleDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineGreatWall.Material.Gbx", [ [ [ "Blend3", [ "AlpineGreatWall.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineRoadChalet.Material.Gbx", [ [ [ "Diffuse", [ "AlpineRoadChaletDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineRaceFlags.Material.Gbx", [ [ [ "Diffuse", [ "AlpineRaceFlags.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineLamp.Material.Gbx", [ [ [ "Diffuse", [ "AlpineLamp.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineMetalGrid.Material.Gbx", [ [ [ "Diffuse", [ "AlpineMetalGrid.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineAsphaltTurbo.Material.Gbx", [ [ [ "Diffuse", [ "AlpineAsphaltTurboDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineRoadWoodTurbo.Material.Gbx", [ [ [ "Diffuse", [ "AlpineRoadWoodTurboDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineAsphaltFreeWheeling.Material.Gbx", [ [ [ "Diffuse", [ "AlpineAsphaltFreeWheeling.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineRoadWoodFreeWheeling.Material.Gbx", [ [ [ "Diffuse", [ "AlpineRoadWoodFreeWheeling.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineTempleAlpha.Material.Gbx", [ [ [ "Diffuse", [ "AlpineTempleDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineAsphaltTurboRoulette.Material.Gbx", [ [ [ "Diffuse", [ "AlpineAsphaltTurboDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ], [ "TurboMask", [ "AlpineAsphaltTurboRouletteDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineRoadWoodTurboRoulette.Material.Gbx", [ [ [ "Diffuse", [ "AlpineRoadWoodTurboDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ], [ "TurboMask", [ "AlpineRoadWoodTurboRouletteDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineTemple.Material.Gbx", [ [ [ "Diffuse", [ "AlpineTempleDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineRaceSigns.Material.Gbx", [ [ [ "Diffuse", [ "AlpineRaceSigns.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineGreatWallCastle.Material.Gbx", [ [ [ "Diffuse", [ "AlpineGreatWallCastle.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineGreatWallRoad.Material.Gbx", [ [ [ "Diffuse", [ "AlpineGreatWallRoad.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "ApineGreatWallHillSnow.Material.Gbx", [ [ [ "Blend3", [ "AlpineGreatWallHill.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "ApineGreatWallHillToundra.Material.Gbx", [ [ [ "Blend3", [ "AlpineGreatWallHill.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineGreatWallToundra.Material.Gbx", [ [ [ "Blend3", [ "AlpineGreatWall.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineTunnelRock.Material.Gbx", [ [ [ "Diffuse", [ "AlpineTunnelDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ], [ [ "PreLight", [ "AlpineTunnelRadiosity.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineTunnelWood.Material.Gbx", [ [ [ "Diffuse", [ "AlpineTunnelDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ], [ [ "PreLight", [ "AlpineTunnelRadiosity.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineTunnelGlowVolume.Material.Gbx", [ [ [ "Diffuse", [ "AlpineTunnelRadiosity.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineTunnelAsphalt.Material.Gbx", [ [ [ "Diffuse", [ "AlpineAsphaltDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ], [ [ "PreLight", [ "AlpineTunnelRadiosity.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineTunnelTurbo.Material.Gbx", [ [ [ "Diffuse", [ "AlpineAsphaltTurboDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ], [ [ "PreLight", [ "AlpineTunnelRadiosity.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineToundraBorders.Material.Gbx", [ [ [ "Blend3", [ "AlpineSnowBorders.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineBark.Material.Gbx", [ [ [ "Diffuse", [ "AlpineBark.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineTrees.Material.Gbx", [ [ [ "Diffuse", [ "AlpineTrees.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
    ( "AlpineAdvertising.Material.Gbx", [ [ [ "Diffuse", [ "Advertisement.dds", "Image", "Texture", "Media", "Interface" ] ] ] ] ),
    ( "AlpineSignsSelfIllum.Material.Gbx", [ [ [ "SelfIllum", [ "AlpineTunnelDiffuse.dds", "Image", "Texture", "Media", "Alpine" ] ] ], [ [ "Anim", [ "AlpineSignsSelfIllum.dds", "Image", "Texture", "Media", "Alpine" ] ] ] ] ),
]