MATERIALS_BAY = [
    ( "BayAdvertisement.Material.Gbx", [ [ [ "Diffuse", [ "Advertisement.dds", "Image", "Texture", "Media", "Interface" ] ] ] ] ),
    ( "BayBridgeAlpha.Material.Gbx", [ [ [ "Diffuse", [ "BayBridgeAlpha.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBridgePillar.Material.Gbx", [ [ [ "Diffuse", [ "BayBridgePillar.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBridgeRedMetal.Material.Gbx", [ [ [ "Diffuse", [ "BayBridgeRedMetal.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBridgeRoad.Material.Gbx", [ [ [ "Diffuse", [ "BayBridgeRoad.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBridgeTurbo.Material.Gbx", [ [ [ "Diffuse", [ "BayBridgeTurbo.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBridgeTurbo2.Material.Gbx", [ [ [ "Diffuse", [ "BayBridgeTurbo2.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBridgeTurboRoulette.Material.Gbx", [ [ [ "Diffuse", [ "BayBridgeTurbo.dds", "Image", "Texture", "Media", "Bay" ] ], [ "TurboMask", [ "BayBridgeTurboRoulette.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBuilding.Material.Gbx", [ [ [ "Diffuse", [ "BayBuilding.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBuildingBase.Material.Gbx", [ [ [ "Diffuse", [ "BayBuildingBase.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBuildingConcrete.Material.Gbx", [ [ [ "Diffuse", [ "BayBuildingConcrete.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayBuildingRoof.Material.Gbx", [ [ [ "Diffuse", [ "BayBuildingRoof.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayCargoSkin.Material.Gbx", [ [ [ "Diffuse", [ "BayCargoSkin.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayCargoUnderSea.Material.Gbx", [ [ [ "Diffuse", [ "BayCargoSkin.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayConcrete.Material.Gbx", [ [ [ "Diffuse", [ "BayConcrete.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayConcrete2.Material.Gbx", [ [ [ "Diffuse", [ "BayConcrete2.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayConcrete2Shiny.Material.Gbx", [ [ [ "Diffuse", [ "BayConcrete2.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayConcrete2UnderSea.Material.Gbx", [ [ [ "Diffuse", [ "BayConcrete2.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayContainer.Material.Gbx", [ [ [ "Diffuse", [ "BayContainer.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDecor.Material.Gbx", [ [ [ "Diffuse", [ "BayDecor.DDS", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDecorAlpha.Material.Gbx", [ [ [ "Diffuse", [ "BayDecorAlpha.DDS", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDecorBase.Material.Gbx", [ [ [ "Diffuse", [ "BayDecorBase.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDocks.Material.Gbx", [ [ [ "Diffuse", [ "BayDocks.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDocksAlpha.Material.Gbx", [ [ [ "Diffuse", [ "BayDocksAlpha.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDocksDecor.Material.Gbx", [ [ [ "Diffuse", [ "BayDocksDecor.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDocksHarbor.Material.Gbx", [ [ [ "Diffuse", [ "BayDocksHarbor.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDocksHarborUnderSea.Material.Gbx", [ [ [ "Diffuse", [ "BayDocksHarbor.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDocksRoad.Material.Gbx", [ [ [ "Diffuse", [ "BayDocksRoad.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayDocksUnderSea.Material.Gbx", [ [ [ "Diffuse", [ "BayDocks.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayFlat.Material.Gbx", [ [ [ "Diffuse", [ "BayFlat.dds", "Image", "Texture", "Media", "Bay" ] ], [ "TransluRGB", [ "BayFlatTrans.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayFlatDetails.Material.Gbx", [ [ [ "Diffuse", [ "BayFlatDetails.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayFluo.Material.Gbx", [] ),
    ( "BayHarborGround.Material.Gbx", [ [ [ "Diffuse", [ "BayHarborGround.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayItemsAlpha.Material.Gbx", [ [ [ "Diffuse", [ "BayItemsAlpha.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayLightVolume.Material.Gbx", [] ),
    ( "BayPlatformFloor.Material.Gbx", [ [ [ "Diffuse", [ "BayPlatformFloor.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayPlatformFloorNC.Material.Gbx", [ [ [ "Diffuse", [ "BayPlatformFloor.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayPlatformTurbo.Material.Gbx", [ [ [ "Diffuse", [ "BayPlatformTurbo.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayPlatformTurbo2.Material.Gbx", [ [ [ "Diffuse", [ "BayPlatformTurbo2.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayRaceSigns.Material.Gbx", [ [ [ "Diffuse", [ "BayRaceSigns.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayRoad.Material.Gbx", [ [ [ "Diffuse", [ "BayRoad.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayRoadSigns.Material.Gbx", [ [ [ "Diffuse", [ "BayRoadSigns.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BaySea.Material.Gbx", [] ),
    ( "BaySeaGround.Material.Gbx", [] ),
    ( "BayShops.Material.Gbx", [ [ [ "Diffuse", [ "BayShops.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayShopsSignsFast.Material.Gbx", [ [ [ "Diffuse", [ "BayShopsSigns.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayShopsSignsFastB.Material.Gbx", [ [ [ "Diffuse", [ "BayShopsSigns.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayShopsSignsMedium.Material.Gbx", [ [ [ "Diffuse", [ "BayShopsSigns.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayShopsSignsSlow.Material.Gbx", [ [ [ "Diffuse", [ "BayShopsSigns.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayShopsSignsSlowB.Material.Gbx", [ [ [ "Diffuse", [ "BayShopsSigns.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BaySigns.Material.Gbx", [ [ [ "Diffuse", [ "BaySigns.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BaySigns2.Material.Gbx", [ [ [ "Diffuse", [ "BaySigns2.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayToll.Material.Gbx", [ [ [ "Diffuse", [ "BayToll.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayTrees.Material.Gbx", [ [ [ "Diffuse", [ "BayTrees.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayTunnel.Material.Gbx", [ [ [ "Diffuse", [ "BayTunnel.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayTunnelRaceSigns.Material.Gbx", [ [ [ "Diffuse", [ "BayRaceSigns.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayTunnelRoad.Material.Gbx", [ [ [ "Diffuse", [ "BayRoad.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayTunnelTurbo.Material.Gbx", [ [ [ "Diffuse", [ "BayTurbo.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayTunnelTurbo2.Material.Gbx", [ [ [ "Diffuse", [ "BayTurbo2.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayTurbo.Material.Gbx", [ [ [ "Diffuse", [ "BayTurbo.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayTurbo2.Material.Gbx", [ [ [ "Diffuse", [ "BayTurbo2.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayTurboRoulette.Material.Gbx", [ [ [ "Diffuse", [ "BayTurbo.dds", "Image", "Texture", "Media", "Bay" ] ], [ "TurboMask", [ "BayTurboRoulette.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayVegetation.Material.Gbx", [ [ [ "Diffuse", [ "BayVegetation.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpAlphaHouses.Material.Gbx", [ [ [ "Diffuse", [ "BayWarpAlphaHouses.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpBeach.Material.Gbx", [ [ [ "Blend3", [ "BayWarpBeach.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpBuildings.Material.Gbx", [ [ [ "Diffuse", [ "BayWarpBuildings.dds", "Image", "Texture", "Media", "Bay" ] ], [ "SelfIllum", [ "WarpBuildingsSelfIllum.dds", "Day", "Moods", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpCityGround.Material.Gbx", [ [ [ "Diffuse", [ "BayWarpCityGround.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpCliff.Material.Gbx", [ [ [ "Blend3", [ "BayWarpCliff.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpDocks.Material.Gbx", [ [ [ "Diffuse", [ "BayDocks.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpFlats.Material.Gbx", [ [ [ "Diffuse", [ "BayWarpFlats.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpGrass.Material.Gbx", [] ),
    ( "BayWarpRoad.Material.Gbx", [ [ [ "Blend3", [ "BayWarpRoad.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpRocks.Material.Gbx", [ [ [ "Blend3", [ "BayWarpRocks.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWarpSea.Material.Gbx", [] ),
    ( "BayWarpSeaGround.Material.Gbx", [] ),
    ( "BayWindows1.Material.Gbx", [ [ [ "Diffuse", [ "BayBuilding1.dds", "Image", "Texture", "Media", "Bay" ] ], [ "TransluRGB", [ "BayBuilding1Trans.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWindows2.Material.Gbx", [ [ [ "Diffuse", [ "BayBuilding2.dds", "Image", "Texture", "Media", "Bay" ] ], [ "TransluRGB", [ "BayBuilding2Trans.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
    ( "BayWindowsTrans.Material.Gbx", [ [ [ "Diffuse", [ "BayWindowsTrans.dds", "Image", "Texture", "Media", "Bay" ] ] ] ] ),
]