MATERIALS_COAST = [
    ( "CoastAsphalt.Material.Gbx", [ [] ] ),
    ( "CoastBoats.Material.Gbx", [ [ [ "Diffuse", [ "CoastBoats.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastBoatsUnderSea.Material.Gbx", [ [ [ "Diffuse", [ "CoastBoats.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCircuit.Material.Gbx", [] ),
    ( "CoastCircuitAdvert.Material.Gbx", [ [ [ "Diffuse", [ "Advertisement.dds", "Image", "Texture", "Media", "Interface" ] ] ] ] ),
    ( "CoastCircuitRumbleStrip.Material.Gbx", [ [ [ "Blend3", [ "CoastCircuitTransitionGrass.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCircuitSigns.Material.Gbx", [ [ [ "Diffuse", [ "CoastCircuitSigns.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCircuitTransition.Material.Gbx", [ [ [ "Blend3", [ "CoastCircuitTransition.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCircuitTransitionGrass.Material.Gbx", [ [ [ "Blend3", [ "CoastCircuitTransitionGrass.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCircuitTurbo.Material.Gbx", [ [ [ "Blend3", [ "CoastCircuitTurbo.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCircuitTurbo2.Material.Gbx", [ [ [ "Blend3", [ "CoastCircuitTurbo2.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCliff.Material.Gbx", [ [ [ "Blend3", [ "CoastCliff.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastConcrete.Material.Gbx", [ [ [ "Diffuse", [ "CoastConcrete.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCorniche.Material.Gbx", [ [ [ "Blend3", [ "CoastCorniche.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCornicheRoad.Material.Gbx", [ [ [ "Diffuse", [ "CoastCornicheRoad.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCornicheTransition.Material.Gbx", [ [ [ "Blend3", [ "CoastCornicheTransition.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastCornicheTransitionRoad.Material.Gbx", [ [ [ "Diffuse", [ "CoastCornicheTransition.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastDecorBase.Material.Gbx", [ [ [ "Blend3", [ "CoastDecorBase.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastDirt.Material.Gbx", [] ),
    ( "CoastFoam.Material.Gbx", [ [ [ "Foam 1", [ "IslandFXFoamStatic.dds", "Image", "Texture", "Media", "Island" ] ], [ "Foam 3", [ "IslandFXFoam2.dds", "Image", "Texture", "Media", "Island" ] ], [ "Foam 2", [ "IslandFXFoam2.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "CoastGrid.Material.Gbx", [ [ [ "Diffuse", [ "CoastGrid.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastItemsAlpha.Material.Gbx", [ [ [ "Diffuse", [ "CoastItemsAlpha.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastPlantes.Material.Gbx", [ [ [ "Diffuse", [ "CoastPlantes.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastRedCobble.Material.Gbx", [] ),
    ( "CoastRoad.Material.Gbx", [ [ [ "Diffuse", [ "CoastRoad.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastRoadBorder.Material.Gbx", [ [ [ "Diffuse", [ "CoastRoad.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastRoadMarks.Material.Gbx", [ [ [ "Diffuse", [ "CoastRoadMarks.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastRoadSigns.Material.Gbx", [ [ [ "Diffuse", [ "CoastRoadSigns.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastRoadSigns2.Material.Gbx", [ [ [ "Diffuse", [ "CoastRoadSigns2.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastRoadTransition.Material.Gbx", [ [ [ "Blend3", [ "CoastRoad.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastRoadTurbo.Material.Gbx", [ [ [ "Diffuse", [ "CoastRoadTurbo.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastRoadTurbo2.Material.Gbx", [ [ [ "Diffuse", [ "CoastRoadTurbo2.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastRoadTurboRoulette.Material.Gbx", [ [ [ "Diffuse", [ "CoastRoadTurbo.dds", "Image", "Texture", "Media", "Coast" ] ], [ "TurboMask", [ "CoastRoadTurboRoulette.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastSea.Material.Gbx", [] ),
    ( "CoastSigns.Material.Gbx", [ [ [ "Diffuse", [ "CoastSigns.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastStone.Material.Gbx", [ [ [ "Diffuse", [ "CoastStone.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastSubSea.Material.Gbx", [] ),
    ( "CoastSubSeaTransition.Material.Gbx", [ [ [ "Blend3", [ "CoastSubSeaTransition.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastTunnel.Material.Gbx", [ [ [ "Diffuse", [ "CoastTunnel.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastTunnelItemsAlpha.Material.Gbx", [ [ [ "Diffuse", [ "CoastItemsAlpha.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastTunnelSigns.Material.Gbx", [ [ [ "Diffuse", [ "CoastTunnelSigns.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastTunnelTurbo.Material.Gbx", [ [ [ "Diffuse", [ "CoastTunnelTurbo.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastTunnelTurbo2.Material.Gbx", [ [ [ "Diffuse", [ "CoastTunnelTurbo2.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastVegetation.Material.Gbx", [ [ [ "Diffuse", [ "CoastVegetation.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastVegetation2.Material.Gbx", [ [ [ "Diffuse", [ "CoastVegetation2.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastVillage.Material.Gbx", [ [ [ "Diffuse", [ "CoastVillage.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastWarpFoam.Material.Gbx", [ [ [ "Foam 1", [ "IslandFXFoamStatic.dds", "Image", "Texture", "Media", "Island" ] ], [ "Foam 3", [ "IslandFXFoam2.dds", "Image", "Texture", "Media", "Island" ] ], [ "Foam 2", [ "IslandFXFoam2.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "CoastWarpForest.Material.Gbx", [ [ [ "Blend3", [ "CoastWarpForest.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastWarpGrass.Material.Gbx", [] ),
    ( "CoastWarpGroundDetails.Material.Gbx", [ [ [ "Blend3", [ "CoastWarpGroundDetails.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastWarpMountains.Material.Gbx", [ [ [ "Blend3", [ "CoastWarpMountains.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastWarpRocks.Material.Gbx", [ [ [ "Blend3", [ "CoastWarpRocks.dds", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastWarpSea.Material.Gbx", [] ),
    ( "CoastWarpSubSea.Material.Gbx", [] ),
    ( "CoastYacht.Material.Gbx", [ [ [ "Diffuse", [ "CoastYacht.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastYachtAlpha.Material.Gbx", [ [ [ "Diffuse", [ "CoastYachtAlpha.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastYachtFloor.Material.Gbx", [ [ [ "Diffuse", [ "CoastYachtFloor.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
    ( "CoastYachtUnderSea.Material.Gbx", [ [ [ "Diffuse", [ "CoastYacht.DDS", "Image", "Texture", "Media", "Coast" ] ] ] ] ),
]