MATERIALS_ISLAND = [
    ( "IslandBeachFoam.Material.Gbx", [ [ [ "Foam 1", [ "IslandFXFoamStatic.dds", "Image", "Texture", "Media", "Island" ] ], [ "Foam 3", [ "IslandFXFoam2.dds", "Image", "Texture", "Media", "Island" ] ], [ "Foam 2", [ "IslandFXFoam2.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandSea.Material.Gbx", [] ),
    ( "IslandSeaGround.Material.Gbx", [] ),
    ( "IslandGrass.Material.Gbx", [] ),
    ( "IslandHighWayBorders.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighWayDiffuse.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighway.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighWayDiffuse.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighWayTransitions.Material.Gbx", [ [ [ "Blend3", [ "IslandHighWayDiffuse.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandRoadSigns.Material.Gbx", [ [ [ "Diffuse", [ "IslandRoadSigns.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandRoadSigns2.Material.Gbx", [ [ [ "Diffuse", [ "IslandRoadSigns2.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandConcrete.Material.Gbx", [ [ [ "Diffuse", [ "IslandConcrete.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandCrashBarrier.Material.Gbx", [ [ [ "Diffuse", [ "IslandCrashBarrier.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandLightVolume.Material.Gbx", [] ),
    ( "IslandLightSigns.Material.Gbx", [ [ [ "SelfIllum", [ "IslandLightSignsGlow.dds", "Image", "Texture", "Media", "Island" ] ] ], [ [ "Anim", [ "IslandLightSignsSequencer.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandPlateformAlpha.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlateformAlpha.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandTransitionBeach.Material.Gbx", [ [ [ "Borders", [ "IslandTransition.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandBeach.Material.Gbx", [] ),
    ( "IslandTransitionGrass.Material.Gbx", [ [ [ "Blend3", [ "IslandTransition.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandBeachUnderSea.Material.Gbx", [ [ [ "Blend3", [ "IslandTransition.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandSky.Material.Gbx", [ [ [ "Clouds", [ "SkyCeiling.dds", "Day", "Moods", "Media", "Island" ] ] ], [ [ "Panorama", [ "SkyPanoramic.dds", "Day", "Moods", "Media", "Island" ] ] ] ] ),
    ( "IslandWarpSeaGround.Material.Gbx", [] ),
    ( "IslandWarpIsleUnderSea.Material.Gbx", [ [ [ "Blend3", [ "IslandWarpIsle.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandWarpIsle.Material.Gbx", [ [ [ "Blend3", [ "IslandWarpIsle.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandWarpShore.Material.Gbx", [ [ [ "Blend3", [ "IslandWarpShore.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandWarpGrass.Material.Gbx", [] ),
    ( "IslandWarpMountains.Material.Gbx", [ [ [ "Blend3", [ "IslandWarpMountains.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandWarpAlpha.Material.Gbx", [ [ [ "Diffuse", [ "IslandWarpAlpha.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandWarpSea.Material.Gbx", [] ),
    ( "IslandItemAlpha1Sided.Material.Gbx", [ [ [ "Diffuse", [ "IslandItemsAlpha.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandPlateform.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlateform.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandFloor.Material.Gbx", [ [ [ "Diffuse", [ "IslandFloor.DDS", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandSpaceLaunch.Material.Gbx", [ [ [ "Diffuse", [ "IslandSpacelaunch.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandItemsAlpha.Material.Gbx", [ [ [ "Diffuse", [ "IslandItemsAlpha.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandSpace.Material.Gbx", [ [ [ "Diffuse", [ "IslandSpace.DDS", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandBuilding.Material.Gbx", [ [ [ "Diffuse", [ "IslandBuilding.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandClub.Material.Gbx", [ [ [ "Diffuse", [ "IslandClub.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandCroisetteTransition.Material.Gbx", [ [ [ "Blend3", [ "IslandCroisette.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandPlateformFloor.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlateformFloor.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandSpaceAlpha.Material.Gbx", [ [ [ "Diffuse", [ "IslandSpaceAlpha.DDS", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandDecorBase.Material.Gbx", [ [ [ "Blend3", [ "IslandDecorBase.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandTrafficLight.Material.Gbx", [ [ [ "Diffuse", [ "IslandTrafficLight.dds", "Image", "Texture", "Media", "Island" ] ], [ "Glow", [ "IslandTrafficLightGlow.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandVegetation.Material.Gbx", [ [ [ "Diffuse", [ "IslandVegetation.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandRoadMarks.Material.Gbx", [ [ [ "Diffuse", [ "IslandRoadmarks.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandVegetationMip.Material.Gbx", [ [ [ "Diffuse", [ "IslandVegetation.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandDecorPlantesMip.Material.Gbx", [ [ [ "Diffuse", [ "IslandDecorPlantes.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandDecorPlantes.Material.Gbx", [ [ [ "Diffuse", [ "IslandDecorPlantes.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandTunnelRoadSigns2.Material.Gbx", [ [ [ "Diffuse", [ "IslandRoadSigns2.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighWayTurbo.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighWayTurbo.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighwayTurbo2.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighWayTurbo2.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighWayTurboRoulette.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighWayTurbo.dds", "Image", "Texture", "Media", "Island" ] ], [ "TurboMask", [ "IslandHighWayTurboRoulette.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandPlateformSpecial.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlateformSpecial.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandSigns.Material.Gbx", [ [ [ "Diffuse", [ "IslandSigns.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighwayTunnel.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighwayTunnel.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighwayTunnelRoad.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighWayDiffuse.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandTunnelRoadSigns.Material.Gbx", [ [ [ "Diffuse", [ "IslandRoadSigns.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandConcreteTunnel.Material.Gbx", [ [ [ "Diffuse", [ "IslandConcrete.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandCroisetteConcrete.Material.Gbx", [ [ [ "Diffuse", [ "IslandCroisette.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandCroisetteAsphalte.Material.Gbx", [ [ [ "Diffuse", [ "IslandCroisette.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandTrees.Material.Gbx", [ [ [ "Diffuse", [ "IslandTrees.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandTreesMip.Material.Gbx", [ [ [ "Diffuse", [ "IslandTrees.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandConcreteUnderSea.Material.Gbx", [ [ [ "Diffuse", [ "IslandConcrete.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandShadowCaster.Material.Gbx", [] ),
    ( "IslandMetal.Material.Gbx", [ [ [ "Diffuse", [ "IslandMetal.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighWayUnderSea.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighWayDiffuse.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandAdvertisement.Material.Gbx", [ [ [ "Diffuse", [ "Advertisement.dds", "Image", "Texture", "Media", "Interface" ] ] ] ] ),
    ( "IslandHotelBase.Material.Gbx", [ [ [ "Blend3", [ "IslandHotelBase.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandWindowsMip.Material.Gbx", [] ),
    ( "IslandPlatformTurbo.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlateformTurbo.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandPlatformTurboRoulette.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlateformTurbo.dds", "Image", "Texture", "Media", "Island" ] ], [ "TurboMask", [ "IslandPlateformTurboRoulette.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandPlatformTurbo2.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlateformTurbo2.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighwayTunnelTurbo.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighWayTurbo.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighwayTunnelTurbo2.Material.Gbx", [ [ [ "Diffuse", [ "IslandHighWayTurbo2.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandHighwayTunnelSigns.Material.Gbx", [ [ [ "Diffuse", [ "IslandSigns.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandBoats.Material.Gbx", [ [ [ "Diffuse", [ "IslandBoats.DDS", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandClubSkin.Material.Gbx", [ [ [ "Diffuse", [ "IslandClubSkin.DDS", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandClubUnderSea.Material.Gbx", [ [ [ "Diffuse", [ "IslandClub.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandBoatsUnderSea.Material.Gbx", [ [ [ "Diffuse", [ "IslandBoats.DDS", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandDecorCliff.Material.Gbx", [ [ [ "Diffuse", [ "IslandDecorCliff.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandAirportTarmac.Material.Gbx", [ [ [ "Diffuse", [ "IslandTarmac.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandPlaneDetail.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlaneDetail.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandPlaneDetailAlpha.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlaneDetail.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandPlaneSkin.Material.Gbx", [ [ [ "Diffuse", [ "IslandPlaneSkin.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandTarmacGrass.Material.Gbx", [] ),
    ( "IslandAirportTarmacTransition.Material.Gbx", [ [ [ "Blend3", [ "IslandTarmac.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
    ( "IslandAirportTarmacBorder.Material.Gbx", [ [ [ "Diffuse", [ "IslandTarmac.dds", "Image", "Texture", "Media", "Island" ] ] ] ] ),
]