MATERIALS_RALLY = [
    ( "RallyGrass2.Material.Gbx", [] ),
    ( "RallyVegetation.Material.Gbx", [ [ [ "Diffuse", [ "RallyVegetation.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyCliff.Material.Gbx", [ [ [ "Borders", [ "RallyCliffDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "DirtyRoad.Material.Gbx", [ [ [ "Diffuse", [ "DirtyRoadDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyGrass2Borders.Material.Gbx", [ [ [ "Borders", [ "RallyGrassBorders.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTreeBranchAlpha.Material.Gbx", [ [ [ "Diffuse", [ "RallyTreeBranchAlpha.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTreeSpriteAlpha.Material.Gbx", [ [ [ "Diffuse", [ "RallyTreeSpriteAlpha.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTreeSpriteAlpha2.Material.Gbx", [ [ [ "Diffuse", [ "RallyTreeSpriteAlpha2.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTreeSpriteAlphaLowQ.Material.Gbx", [ [ [ "Diffuse", [ "RallyTreeSpriteAlpha.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTreeSpriteAlpha2LowQ.Material.Gbx", [ [ [ "Diffuse", [ "RallyTreeSpriteAlpha2.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyLakeGround.Material.Gbx", [] ),
    ( "RallyWater.Material.Gbx", [] ),
    ( "RallyLakeWaterBorders.Material.Gbx", [ [ [ "Diffuse", [ "RallyLakeBorderDiff.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyRockyGrass.Material.Gbx", [] ),
    ( "RallyRockyGrassCliff.Material.Gbx", [ [ [ "Blend3", [ "RallyRockyGrassCliff.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyGrassCliff.Material.Gbx", [ [ [ "Borders", [ "RallyRockyGrassCliff.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyWarpGrass.Material.Gbx", [] ),
    ( "RallyWarpCliff.Material.Gbx", [ [ [ "Borders", [ "RallyCliffDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyWarpLake.Material.Gbx", [] ),
    ( "RallyWarpTrees.Material.Gbx", [ [ [ "Diffuse", [ "RallyWarpTrees.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyWarpShadowCaster.Material.Gbx", [] ),
    ( "RallyCastle.Material.Gbx", [ [ [ "Diffuse", [ "RallyCastle.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyWoodBridge.Material.Gbx", [ [ [ "Diffuse", [ "RallyWoodBridge.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyFlags.Material.Gbx", [ [ [ "Diffuse", [ "RallyFlagDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTrunk.Material.Gbx", [ [ [ "Diffuse", [ "Trunk.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyHouse.Material.Gbx", [ [ [ "Diffuse", [ "RallyHouse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyWhiteWood.Material.Gbx", [ [ [ "Diffuse", [ "RallyWhiteWood.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyRoadMedium.Material.Gbx", [ [ [ "Diffuse", [ "RallyRoadMediumDiffuse2.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyRoadSigns.Material.Gbx", [ [ [ "Diffuse", [ "RallyRoadSigns.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyCastleArrow.Material.Gbx", [ [ [ "Diffuse", [ "RallyCastleHarrows.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyCastleBridge.Material.Gbx", [ [ [ "Diffuse", [ "RallyCastleBridge.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyRoadMediumTurbo.Material.Gbx", [ [ [ "Diffuse", [ "RallyRoadMediumTurboDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTurboRoulette.Material.Gbx", [ [ [ "Diffuse", [ "RallyRoadMediumTurboDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ], [ "TurboMask", [ "RallyRoadMediumTurboRouletteDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyRoadMediumFreeWheeling.Material.Gbx", [ [ [ "Diffuse", [ "RallyRoadMediumFreeWheeling.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTunnelCastle.Material.Gbx", [ [ [ "Diffuse", [ "RallyCastle.dds", "Image", "Texture", "Media", "Rally" ] ] ], [ [ "PreLight", [ "RallyTunnelRadiosity.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTunnelRoadMedium.Material.Gbx", [ [ [ "Diffuse", [ "RallyRoadMediumDiffuse2.dds", "Image", "Texture", "Media", "Rally" ] ] ], [ [ "PreLight", [ "RallyTunnelRadiosity.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTunnelGlowVolume.Material.Gbx", [ [], [ [ "Diffuse", [ "RallyTunnelRadiosity.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTunnelFlags.Material.Gbx", [ [ [ "Diffuse", [ "RallyFlagDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ], [ [ "PreLight", [ "RallyTunnelRadiosity.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyTunnelTurbo.Material.Gbx", [ [ [ "Diffuse", [ "RallyRoadMediumTurboDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ], [ [ "PreLight", [ "RallyTunnelRadiosity.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyRoadMediumToLow.Material.Gbx", [ [ [ "Diffuse", [ "RallyRoadLowtoMediumDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyRoadLowtoMedium.Material.Gbx", [ [ [ "Diffuse", [ "RallyRoadLowtoMediumDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyStoneBridge.Material.Gbx", [ [ [ "Diffuse", [ "RallyStoneBridge.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyCastleUnderWater.Material.Gbx", [ [ [ "Diffuse", [ "RallyCastle.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyStoneBridgeUnderWater.Material.Gbx", [ [ [ "Diffuse", [ "RallyStoneBridge.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyFieldBorders.Material.Gbx", [ [ [ "Borders", [ "RallyFieldBorders.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyField.Material.Gbx", [ [ [ "Diffuse", [ "RallyField.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyFieldVegetation.Material.Gbx", [ [ [ "Diffuse", [ "RallyFieldVegetation.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyFieldRouleau.Material.Gbx", [ [ [ "Diffuse", [ "RallyFieldRouleau.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyWindMillWings.Material.Gbx", [ [ [ "Diffuse", [ "RallyWindMillDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyWindMill.Material.Gbx", [ [ [ "Diffuse", [ "RallyWindMillDiffuse.dds", "Image", "Texture", "Media", "Rally" ] ] ] ] ),
    ( "RallyAdvertising.Material.Gbx", [ [ [ "Diffuse", [ "Advertisement.dds", "Image", "Texture", "Media", "Interface" ] ] ] ] ),
]