MATERIALS_SPEED = [
    ( "SpeedAdvertising.Material.Gbx", [ [ [ "Diffuse", [ "Advertisement.dds", "Image", "Texture", "Media", "Interface" ] ] ] ] ),
    ( "SpeedAnimatedTrafficLight.Material.Gbx", [ [ [ "Diffuse", [ "SpeedTrafficLightDiffuse.dds", "Image", "Texture", "Media", "Speed" ] ], [ "Glow", [ "SpeedTrafficLightGlow.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedAsphalt.Material.Gbx", [ [ [ "Diffuse", [ "SpeedAsphalt.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedBridgeAlpha.Material.Gbx", [ [ [ "Diffuse", [ "SpeedBridgeAlpha.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedBrushedMetal.Material.Gbx", [ [ [ "Diffuse", [ "SpeedBrushedMetal.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedCanyonWarp.Material.Gbx", [ [ [ "Blend3", [ "SpeedCanyonWarp.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedCanyonWarp2.Material.Gbx", [ [ [ "Blend3", [ "SpeedCanyonWarp2.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedCliff2.Material.Gbx", [ [ [ "Blend3", [ "SpeedCliff2.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedCliff2Plant.Material.Gbx", [ [ [ "Diffuse", [ "SpeedCliff2Plant.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedCliff2Rock.Material.Gbx", [] ),
    ( "SpeedCliff2Sand.Material.Gbx", [ [ [ "Blend3", [ "SpeedCliff2.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedConcrete.Material.Gbx", [ [ [ "Diffuse", [ "SpeedConcrete.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedConcreteBorder.Material.Gbx", [ [ [ "Diffuse", [ "SpeedConcreteBorder.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedConcreteUnderWater.Material.Gbx", [ [ [ "Diffuse", [ "SpeedConcrete.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedCrashBarrier.Material.Gbx", [ [ [ "Diffuse", [ "SpeedCrashBarrier.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedDecors.Material.Gbx", [ [ [ "Diffuse", [ "SpeedDecors.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedDerrickAlphas.Material.Gbx", [ [ [ "Diffuse", [ "echelle.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedFreeWheeling.Material.Gbx", [ [ [ "Diffuse", [ "SpeedFreeWheeling.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedMetalAlphas.Material.Gbx", [ [ [ "Diffuse", [ "SpeedMetalAlphas.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedMetalGrid.Material.Gbx", [ [ [ "Diffuse", [ "SpeedMetalGrid.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedParkingAsphalt.Material.Gbx", [ [ [ "Borders", [ "SpeedParkingMarks.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedParkingTurbo.Material.Gbx", [ [ [ "Borders", [ "SpeedParkingTurbo.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedRiver.Material.Gbx", [] ),
    ( "SpeedRiverBeach.Material.Gbx", [ [ [ "Blend3", [ "SpeedRiverBeach.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedRiverBeachUnderWater.Material.Gbx", [ [ [ "Blend3", [ "SpeedRiverBeach.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedRoadSigns.Material.Gbx", [ [ [ "Diffuse", [ "SpeedRoadSigns.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedRock.Material.Gbx", [ [ [ "Diffuse", [ "SpeedRock.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedSaguaro.Material.Gbx", [ [ [ "Diffuse", [ "SpeedSaguaro.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedSand.Material.Gbx", [] ),
    ( "SpeedSandBorder.Material.Gbx", [ [ [ "Blend3", [ "SpeedSandBorder.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedSky.Material.Gbx", [ [ [ "Clouds", [ "SkyCeiling.dds", "Day", "Moods", "Media", "Speed" ] ] ], [ [ "Panorama", [ "SkyPanoramic.dds", "Day", "Moods", "Media", "Speed" ] ] ] ] ),
    ( "SpeedTunnelAsphalt.Material.Gbx", [ [ [ "Diffuse", [ "SpeedAsphalt.dds", "Image", "Texture", "Media", "Speed" ] ] ], [ [ "PreLight", [ "SpeedTunnelRadiosity.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedTunnelConcrete.Material.Gbx", [ [ [ "Diffuse", [ "SpeedConcrete.dds", "Image", "Texture", "Media", "Speed" ] ] ], [ [ "PreLight", [ "SpeedTunnelRadiosity.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedTunnelDecors.Material.Gbx", [ [ [ "Diffuse", [ "SpeedDecors.dds", "Image", "Texture", "Media", "Speed" ] ] ], [ [ "PreLight", [ "SpeedTunnelRadiosity.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedTunnelRoadSigns.Material.Gbx", [ [ [ "Diffuse", [ "SpeedRoadSigns.dds", "Image", "Texture", "Media", "Speed" ] ] ], [ [ "PreLight", [ "SpeedTunnelRadiosity.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedTunnelTurbo.Material.Gbx", [ [ [ "Diffuse", [ "SpeedTurbo.dds", "Image", "Texture", "Media", "Speed" ] ] ], [ [ "PreLight", [ "SpeedTunnelRadiosity.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedTurbo.Material.Gbx", [ [ [ "Diffuse", [ "SpeedTurbo.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedTurboRoulette.Material.Gbx", [ [ [ "Diffuse", [ "SpeedTurbo.dds", "Image", "Texture", "Media", "Speed" ] ], [ "TurboMask", [ "SpeedTurboRouletteMask.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
    ( "SpeedWater.Material.Gbx", [] ),
    ( "SpeedWoodPlanks.Material.Gbx", [ [ [ "Diffuse", [ "SpeedWoodPlanks.dds", "Image", "Texture", "Media", "Speed" ] ] ] ] ),
]