MATERIALS_STADIUM = [
(
"StadiumPlatform.Material.Gbx",
"StadiumPlatform",
"""
This material uses:
    - StadiumPlatformD.dds (1st UV layer)
    - StadiumPlatformS.dds (1st UV layer)
    - StadiumPlatformN.dds (1st UV layer)
    - StadiumRoadO2.dds (2nd UV layer)
""",
),
(
"StadiumFabricAuvent2.Material.Gbx",
"StadiumFabricAuvent2",
"StadiumFabricAuvent2",
),
(
"StadiumCircuit.Material.Gbx",
"StadiumCircuit",
"StadiumCircuit",
),
(
"StadiumDirt.Material.Gbx",
"StadiumDirt",
"StadiumDirt",
),
(
"StadiumGrass9m.Material.Gbx",
"StadiumGrass",
"StadiumGrass",
),
(
"StadiumWater.Material.Gbx",
"StadiumWater",
"StadiumWater",
),
(
"StadiumPlatformFloor.Material.Gbx",
"StadiumPlatformFloor",
"StadiumPlatformFloor",
),
(
"StadiumFabricBorderRubber.Material.Gbx",
"StadiumFabricBorderRubber",
"StadiumFabricBorderRubber",
),
(
"StadiumRoadGrid.Material.Gbx",
"StadiumRoadGrid",
"StadiumRoadGrid",
),
(
"StadiumRoad.Material.Gbx",
"StadiumRoad",
"StadiumRoad",
),
(
"StadiumRoadDetails.Material.Gbx",
"StadiumRoadDetails",
"StadiumRoadDetails"
),
(
"StadiumControlInterior.Material.Gbx",
"StadiumControlInterior",
"StadiumControlInterior"
),
(
"StadiumFabricStands2.Material.Gbx",
"StadiumFabricStands2",
"StadiumFabricStands2"
),
(
"StadiumRoadCircuitBorder.Material.Gbx",
"StadiumRoadCircuitBorder",
"StadiumRoadCircuitBorder"
),
(
"StadiumCircuitLogo.Material.Gbx",
"StadiumCircuitLogo",
"StadiumCircuitLogo"
),
(
"StadiumCircuitScreen.Material.Gbx",
"StadiumCircuitScreen",
"StadiumCircuitScreen"
),
(
"StadiumRaceSignsRubber.Material.Gbx",
"StadiumRaceSignsRubber",
"StadiumRaceSignsRubber"
),
(
"StadiumRoadTurbo.Material.Gbx",
"StadiumRoadTurbo",
"StadiumRoadTurbo"
),
(
"StadiumFan.Material.Gbx",
"StadiumFan",
"StadiumFan"
),
(
"StadiumRoadTurboRoulette.Material.Gbx",
"StadiumRoadTurboRoulette",
"StadiumRoadTurboRoulette"
),
(
"StadiumRoadFreeWheeling.Material.Gbx",
"StadiumRoadFreeWheeling",
"StadiumRoadFreeWheeling"
),
(
"StadiumDirtRoad.Material.Gbx",
"StadiumDirtRoad",
"StadiumDirtRoad"
),
(
"StadiumDirtToRoad.Material.Gbx",
"StadiumDirtToRoad",
"StadiumDirtToRoad"
),
(
"StadiumControlLogos.Material.Gbx",
"StadiumControlLogos",
"StadiumControlLogos"
),
(
"StadiumPillar.Material.Gbx",
"StadiumPillar",
"StadiumPillar"
),
(
"StadiumPlatformSoundSystem.Material.Gbx",
"StadiumPlatformSoundSystem",
"StadiumPlatformSoundSystem"
),
(
"StadiumPlatformAuventAlpha.Material.Gbx",
"StadiumPlatformAuventAlpha",
"StadiumPlatformAuventAlpha"
),
(
"StadiumStructureAlpha.Material.Gbx",
"StadiumStructureAlpha",
"StadiumStructureAlpha"
),
(
"StadiumFabricStructure.Material.Gbx",
"StadiumFabricStructure",
"StadiumFabricStructure"
),
(
"StadiumFabric.Material.Gbx",
"StadiumFabric",
"StadiumFabric"
),
(
"StadiumInflatable2.Material.Gbx",
"StadiumInflatable2",
"StadiumInflatable2"
),
(
"StadiumPlatformPillar.Material.Gbx",
"StadiumPlatformPillar",
"StadiumPlatformPillar"
),
(
"StadiumSculpt.Material.Gbx",
"StadiumSculpt",
"StadiumSculpt"
),
(
"StadiumSculpt2.Material.Gbx",
"StadiumSculpt2",
"StadiumSculpt2"
),
(
"StadiumStartLogo.Material.Gbx",
"StadiumStartLogo",
"StadiumStartLogo"
),
(
"StadiumTurboSpots.Material.Gbx",
"StadiumTurboSpots",
"StadiumTurboSpots"
),
(
"StadiumRoadRace.Material.Gbx",
"StadiumRoadRace",
"StadiumRoadRace"
),
(
"StadiumPubNvidiaWorldcup.Material.Gbx",
"StadiumPubNvidiaWorldcup",
"StadiumPubNvidiaWorldcup"
),
(
"StadiumInflatableCastle.Material.Gbx",
"StadiumInflatableCastle",
"StadiumInflatableCastle"
),
(
"StadiumInflatableCactus.Material.Gbx",
"StadiumInflatableCactus",
"StadiumInflatableCactus"
),
(
"StadiumInflatableSnowTree.Material.Gbx",
"StadiumInflatableSnowTree",
"StadiumInflatableSnowTree"
),
(
"StadiumInflatablePalmTree.Material.Gbx",
"StadiumInflatablePalmTree",
"StadiumInflatablePalmTree"
),
(
"StadiumAirship.Material.Gbx",
"StadiumAirship",
"StadiumAirship"
),
(
"StadiumControlGlass.Material.Gbx",
"StadiumControlGlass",
"StadiumControlGlass"
),
(
"StadiumInflatable.Material.Gbx",
"StadiumInflatable",
"StadiumInflatable"
),
(
"StadiumStructureGeneric.Material.Gbx",
"StadiumStructureGeneric",
"StadiumStructureGeneric"
),
(
"StadiumControlStands.Material.Gbx",
"StadiumControlStands",
"StadiumControlStands"
),
(
"StadiumDirtGrid.Material.Gbx",
"StadiumDirtGrid",
"StadiumDirtGrid"
),
(
"StadiumFabricPool.Material.Gbx",
"StadiumFabricPool",
"StadiumFabricPool"
),
(
"StadiumWarpParvis.Material.Gbx",
"StadiumWarpParvis",
"StadiumWarpParvis"
),
(
"StadiumWarpRoute.Material.Gbx",
"StadiumWarpRoute",
"StadiumWarpRoute"
),
(
"StadiumWarpParking.Material.Gbx",
"StadiumWarpParking",
"StadiumWarpParking"
),
(
"StadiumWarpGlass.Material.Gbx",
"StadiumWarpGlass",
"StadiumWarpGlass"
),
]